spring:
  datasource:
    driverClassName: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${DATASOURCE_URL:jdbc:mysql://47.106.92.100:3306/erp_sso_oidc?useUnicode=true&characterEncoding=UTF-8}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:123456}

    redis:
      database: ${REDIS_DATABASE:0}
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
      timeout: ${REDIS_TIMEOUT:10000}

pagehelper:
  params: count=countSql
  helper-dialect: mysql

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
#  type-handlers-package: com.yjyz.erp.customer.srv.utils.handler

logging:
  config: classpath:logback.xml
  level:
    root: info